//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SpringBoxes
{
    [Serializable]
    public class ObjectStateMsg : Message
    {
        public const string k_RosMessageName = "spring_boxes/ObjectState";
        public override string RosMessageName => k_RosMessageName;

        public string id;
        public Geometry.PointMsg position;
        public Geometry.Vector3Msg velocity;

        public ObjectStateMsg()
        {
            this.id = "";
            this.position = new Geometry.PointMsg();
            this.velocity = new Geometry.Vector3Msg();
        }

        public ObjectStateMsg(string id, Geometry.PointMsg position, Geometry.Vector3Msg velocity)
        {
            this.id = id;
            this.position = position;
            this.velocity = velocity;
        }

        public static ObjectStateMsg Deserialize(MessageDeserializer deserializer) => new ObjectStateMsg(deserializer);

        private ObjectStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            this.position = Geometry.PointMsg.Deserialize(deserializer);
            this.velocity = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.position);
            serializer.Write(this.velocity);
        }

        public override string ToString()
        {
            return "ObjectStateMsg: " +
            "\nid: " + id.ToString() +
            "\nposition: " + position.ToString() +
            "\nvelocity: " + velocity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
