//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SpringBoxes
{
    [Serializable]
    public class SpringSystemStateMsg : Message
    {
        public const string k_RosMessageName = "spring_boxes/SpringSystemState";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PointMsg obj1position;
        public Geometry.PointMsg obj2position;

        public SpringSystemStateMsg()
        {
            this.obj1position = new Geometry.PointMsg();
            this.obj2position = new Geometry.PointMsg();
        }

        public SpringSystemStateMsg(Geometry.PointMsg obj1position, Geometry.PointMsg obj2position)
        {
            this.obj1position = obj1position;
            this.obj2position = obj2position;
        }

        public static SpringSystemStateMsg Deserialize(MessageDeserializer deserializer) => new SpringSystemStateMsg(deserializer);

        private SpringSystemStateMsg(MessageDeserializer deserializer)
        {
            this.obj1position = Geometry.PointMsg.Deserialize(deserializer);
            this.obj2position = Geometry.PointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.obj1position);
            serializer.Write(this.obj2position);
        }

        public override string ToString()
        {
            return "SpringSystemStateMsg: " +
            "\nobj1position: " + obj1position.ToString() +
            "\nobj2position: " + obj2position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
