//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SpringBoxes
{
    [Serializable]
    public class UnityUpdateMsg : Message
    {
        public const string k_RosMessageName = "spring_boxes/UnityUpdate";
        public override string RosMessageName => k_RosMessageName;

        public int simState;
        public BoxDataMsg box1data;
        public BoxDataMsg box2data;
        public SystemParamsMsg systemParams;
        public double timeDelta;

        public UnityUpdateMsg()
        {
            this.simState = 0;
            this.box1data = new BoxDataMsg();
            this.box2data = new BoxDataMsg();
            this.systemParams = new SystemParamsMsg();
            this.timeDelta = 0.0;
        }

        public UnityUpdateMsg(int simState, BoxDataMsg box1data, BoxDataMsg box2data, SystemParamsMsg systemParams, double timeDelta)
        {
            this.simState = simState;
            this.box1data = box1data;
            this.box2data = box2data;
            this.systemParams = systemParams;
            this.timeDelta = timeDelta;
        }

        public static UnityUpdateMsg Deserialize(MessageDeserializer deserializer) => new UnityUpdateMsg(deserializer);

        private UnityUpdateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.simState);
            this.box1data = BoxDataMsg.Deserialize(deserializer);
            this.box2data = BoxDataMsg.Deserialize(deserializer);
            this.systemParams = SystemParamsMsg.Deserialize(deserializer);
            deserializer.Read(out this.timeDelta);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.simState);
            serializer.Write(this.box1data);
            serializer.Write(this.box2data);
            serializer.Write(this.systemParams);
            serializer.Write(this.timeDelta);
        }

        public override string ToString()
        {
            return "UnityUpdateMsg: " +
            "\nsimState: " + simState.ToString() +
            "\nbox1data: " + box1data.ToString() +
            "\nbox2data: " + box2data.ToString() +
            "\nsystemParams: " + systemParams.ToString() +
            "\ntimeDelta: " + timeDelta.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
