//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SpringBoxes
{
    [Serializable]
    public class UnityUpdateMsg : Message
    {
        public const string k_RosMessageName = "spring_boxes/UnityUpdate";
        public override string RosMessageName => k_RosMessageName;

        public int simState;
        public UnityObjDataMsg[] objDataList;
        public SystemParamsMsg systemParams;
        public double timeDelta;

        public UnityUpdateMsg()
        {
            this.simState = 0;
            this.objDataList = new UnityObjDataMsg[2];
            this.systemParams = new SystemParamsMsg();
            this.timeDelta = 0.0;
        }

        public UnityUpdateMsg(int simState, UnityObjDataMsg[] objDataList, SystemParamsMsg systemParams, double timeDelta)
        {
            this.simState = simState;
            this.objDataList = objDataList;
            this.systemParams = systemParams;
            this.timeDelta = timeDelta;
        }

        public static UnityUpdateMsg Deserialize(MessageDeserializer deserializer) => new UnityUpdateMsg(deserializer);

        private UnityUpdateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.simState);
            deserializer.Read(out this.objDataList, UnityObjDataMsg.Deserialize, 2);
            this.systemParams = SystemParamsMsg.Deserialize(deserializer);
            deserializer.Read(out this.timeDelta);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.simState);
            serializer.Write(this.objDataList);
            serializer.Write(this.systemParams);
            serializer.Write(this.timeDelta);
        }

        public override string ToString()
        {
            return "UnityUpdateMsg: " +
            "\nsimState: " + simState.ToString() +
            "\nobjDataList: " + System.String.Join(", ", objDataList.ToList()) +
            "\nsystemParams: " + systemParams.ToString() +
            "\ntimeDelta: " + timeDelta.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
