//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SpringBoxes
{
    [Serializable]
    public class SpringOdeSolverRequest : Message
    {
        public const string k_RosMessageName = "spring_boxes/SpringOdeSolver";
        public override string RosMessageName => k_RosMessageName;

        public int simState;
        public bool obj1update;
        public bool obj2update;
        public Geometry.PointMsg obj1initial;
        public Geometry.PointMsg obj2initial;
        public double obj1mass;
        public double obj2mass;
        public double spring_constant;
        public double damper_constant;
        public double equil_spring_length;
        public double timeDelta;

        public SpringOdeSolverRequest()
        {
            this.simState = 0;
            this.obj1update = false;
            this.obj2update = false;
            this.obj1initial = new Geometry.PointMsg();
            this.obj2initial = new Geometry.PointMsg();
            this.obj1mass = 0.0;
            this.obj2mass = 0.0;
            this.spring_constant = 0.0;
            this.damper_constant = 0.0;
            this.equil_spring_length = 0.0;
            this.timeDelta = 0.0;
        }

        public SpringOdeSolverRequest(int simState, bool obj1update, bool obj2update, Geometry.PointMsg obj1initial, Geometry.PointMsg obj2initial, double obj1mass, double obj2mass, double spring_constant, double damper_constant, double equil_spring_length, double timeDelta)
        {
            this.simState = simState;
            this.obj1update = obj1update;
            this.obj2update = obj2update;
            this.obj1initial = obj1initial;
            this.obj2initial = obj2initial;
            this.obj1mass = obj1mass;
            this.obj2mass = obj2mass;
            this.spring_constant = spring_constant;
            this.damper_constant = damper_constant;
            this.equil_spring_length = equil_spring_length;
            this.timeDelta = timeDelta;
        }

        public static SpringOdeSolverRequest Deserialize(MessageDeserializer deserializer) => new SpringOdeSolverRequest(deserializer);

        private SpringOdeSolverRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.simState);
            deserializer.Read(out this.obj1update);
            deserializer.Read(out this.obj2update);
            this.obj1initial = Geometry.PointMsg.Deserialize(deserializer);
            this.obj2initial = Geometry.PointMsg.Deserialize(deserializer);
            deserializer.Read(out this.obj1mass);
            deserializer.Read(out this.obj2mass);
            deserializer.Read(out this.spring_constant);
            deserializer.Read(out this.damper_constant);
            deserializer.Read(out this.equil_spring_length);
            deserializer.Read(out this.timeDelta);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.simState);
            serializer.Write(this.obj1update);
            serializer.Write(this.obj2update);
            serializer.Write(this.obj1initial);
            serializer.Write(this.obj2initial);
            serializer.Write(this.obj1mass);
            serializer.Write(this.obj2mass);
            serializer.Write(this.spring_constant);
            serializer.Write(this.damper_constant);
            serializer.Write(this.equil_spring_length);
            serializer.Write(this.timeDelta);
        }

        public override string ToString()
        {
            return "SpringOdeSolverRequest: " +
            "\nsimState: " + simState.ToString() +
            "\nobj1update: " + obj1update.ToString() +
            "\nobj2update: " + obj2update.ToString() +
            "\nobj1initial: " + obj1initial.ToString() +
            "\nobj2initial: " + obj2initial.ToString() +
            "\nobj1mass: " + obj1mass.ToString() +
            "\nobj2mass: " + obj2mass.ToString() +
            "\nspring_constant: " + spring_constant.ToString() +
            "\ndamper_constant: " + damper_constant.ToString() +
            "\nequil_spring_length: " + equil_spring_length.ToString() +
            "\ntimeDelta: " + timeDelta.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
