//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SpringBoxes
{
    [Serializable]
    public class SpringOdeSolverResponse : Message
    {
        public const string k_RosMessageName = "spring_boxes/SpringOdeSolver";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PointMsg obj1final;
        public Geometry.PointMsg obj2final;

        public SpringOdeSolverResponse()
        {
            this.obj1final = new Geometry.PointMsg();
            this.obj2final = new Geometry.PointMsg();
        }

        public SpringOdeSolverResponse(Geometry.PointMsg obj1final, Geometry.PointMsg obj2final)
        {
            this.obj1final = obj1final;
            this.obj2final = obj2final;
        }

        public static SpringOdeSolverResponse Deserialize(MessageDeserializer deserializer) => new SpringOdeSolverResponse(deserializer);

        private SpringOdeSolverResponse(MessageDeserializer deserializer)
        {
            this.obj1final = Geometry.PointMsg.Deserialize(deserializer);
            this.obj2final = Geometry.PointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.obj1final);
            serializer.Write(this.obj2final);
        }

        public override string ToString()
        {
            return "SpringOdeSolverResponse: " +
            "\nobj1final: " + obj1final.ToString() +
            "\nobj2final: " + obj2final.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
